# Travis-CI is really not suited to using multiple languages at this time so
# we want to build using the minimal package which includes NodeJS and Python
# as well as Docker. We can try to spin up two Docker environments to build and
# and test both the JS and Python code in parallel.
language: minimal
sudo: required
jobs:
  include:
    - stage: Backend
      name: "Install and Lint Backend"
      script:
        - cd backend
        - sudo pip3 install pipenv -qq
        - pipenv install
        - flake8
    - stage: Frontend
      name: "Install and Lint Frontend"
      script:
        - cd frontend
        - npm install
        - eslint src\
